# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Plata Hill <plata.hill@kdemail.net>
---
app-id: org.kde.kalm
runtime: org.kde.Platform
runtime-version: 6.9
sdk: org.kde.Sdk
command: kalm
copy-icon: true
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
cleanup:
  - /include
  - /lib/cmake
  - /lib/libexec
  - /mkspecs
  - /etc/xdg/*categories
  - /share/qlogging-categories5
modules:
  - name: kirigami-addons
    buildsystem: cmake-ninja
    config-opts:
      - "-DBUILD_TESTING=OFF"
    sources:
      - type: archive
        url: https://download.kde.org/stable/kirigami-addons/kirigami-addons-1.8.1.tar.xz
        sha256: 00028ae4df99e250518345ea28d9cdf49d700e9acac482734bb51384da11f945
        x-checker-data:
          type: anitya
          project-id: 242933
          stable-only: true
          url-template: https://download.kde.org/stable/kirigami-addons/kirigami-addons-$version.tar.xz
  - name: kalm
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: '.'
