# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Plata Hill <plata.hill@kdemail.net>
---
app-id: org.kde.kalm
runtime: org.kde.Platform
runtime-version: 5.15-23.08
sdk: org.kde.Sdk
command: kalm
copy-icon: true
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
modules:
  - name: "kirigami-addons"
    config-opts:
      - "-DBUILD_TESTING=OFF"
      - "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    buildsystem: "cmake-ninja"
    sources:
      - type: "archive"
        url: "https://download.kde.org/stable/kirigami-addons/kirigami-addons-0.11.0.tar.xz"
        sha256: "05296c5afbe6804308bf9c0d2751f3b748b40d00fa784946d1dcdf3af4bffbad"
        x-checker-data:
          type: "anitya"
          project-id: 242933
          stable-only: true
          url-template: "https://download.kde.org/stable/kirigami-addons/kirigami-addons-$version.tar.xz"
  - name: kalm
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: '.'
