# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Plata Hill <plata.hill@kdemail.net>
---
app-id: org.kde.kalm
runtime: org.kde.Platform
runtime-version: 6.6-kf6preview
sdk: org.kde.Sdk
command: kalm
copy-icon: true
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
modules:
  - name: "kirigami-addons"
    config-opts:
      - "-DBUILD_TESTING=OFF"
      - "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    buildsystem: "cmake-ninja"
    sources:
      - type: "git"
        url: "https://invent.kde.org/libraries/kirigami-addons.git"
  - name: kalm
    buildsystem: cmake-ninja
    config-opts:
      - "-DBUILD_WITH_QT6=ON"
    sources:
      - type: dir
        path: '.'
