# SPDX-FileCopyrightText: 2023 Plata Hill <plata.hill@kdemail.net>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on':
      - Android/Qt5
      - FreeBSD/Qt5
      - Linux/Qt5
      - Windows/Qt5
    require:
      frameworks/extra-cmake-modules: '@stable'
      frameworks/kcoreaddons: '@stable'
      frameworks/kconfig: '@stable'
      frameworks/ki18n: '@stable'
      frameworks/kirigami: '@stable'
      libraries/kirigami-addons: '@latest'
  - 'on':
      - FreeBSD/Qt5
      - Linux/Qt5
      - Windows/Qt5
    require:
      frameworks/kcrash: '@stable'

  - 'on':
      - Android/Qt6
      - FreeBSD/Qt6
      - Linux/Qt6
      - Windows/Qt6
    require:
      frameworks/extra-cmake-modules: '@latest-kf6'
      frameworks/kcoreaddons: '@latest-kf6'
      frameworks/kconfig: '@latest-kf6'
      frameworks/ki18n: '@latest-kf6'
      frameworks/kirigami: '@latest-kf6'
      libraries/kirigami-addons: '@latest-kf6'
  - 'on':
      - FreeBSD/Qt6
      - Linux/Qt6
      - Windows/Qt6
    require:
      frameworks/kcrash: '@latest-kf6'

Options:
  require-passing-tests-on:
    - '@all'
