# SPDX-FileCopyrightText: 2023 Plata Hill <plata.hill@kdemail.net>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on':
      - Android/Qt6
      - FreeBSD/Qt6
      - Linux/Qt6
      - Linux/Qt6Next
      - Windows/Qt6
    require:
      frameworks/extra-cmake-modules: '@latest-kf6'
      frameworks/kcoreaddons: '@latest-kf6'
      frameworks/kconfig: '@latest-kf6'
      frameworks/ki18n: '@latest-kf6'
      frameworks/kirigami: '@latest-kf6'
      libraries/kirigami-addons: '@latest-kf6'
  - 'on':
      - FreeBSD/Qt6
      - Linux/Qt6
      - Linux/Qt6Next
      - Windows/Qt6
    require:
      frameworks/kcrash: '@latest-kf6'
      frameworks/qqc2-desktop-style: '@latest-kf6'

Options:
  cmake-options: '-DCMAKE_COMPILE_WARNING_AS_ERROR=ON'
  require-passing-tests-on:
    - '@all'
  run-qmllint: true
